//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Action_Item
    {
        public int ActionItemID { get; set; }
        [Display(Name ="Title") ]
        public string ActionItem_Title { get; set; }
        [Display(Name = "Project Name")]
        public string project_Name { get; set; }
        [Display(Name = "Date")]
        public string ActionDate { get; set; }
        [Display(Name = "Time")]
        public string ActionTime { get; set; }
        [Display(Name = "Assigned To")]
        public string ActionAssignedTo { get; set; }
    }
}
