//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int AttendanceID { get; set; }
        public Nullable<int> AppUserID { get; set; }
        public Nullable<int> MeetingID { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<int> IsActive { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Meeting Meeting { get; set; }
    }
}
