//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Decision_Item
    {
        public int DecisionItemID { get; set; }
        [Display(Name = "Decision Title")]
        public string DecisionItem_Title { get; set; }
        [Display(Name = "Project Name")]
        public string project_Name { get; set; }
        public string Description { get; set; }
        [Display(Name = "Date")]
        public string DecisionDate { get; set; }
        [Display(Name = "Time")]
        public string DecisionTime { get; set; }
        [Display(Name = "Assigned To")]
        public string DecisionAssignedTo { get; set; }
        public string Priority { get; set; }
    }
}
