//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_App.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Meeting
    {
        public int MeetingID { get; set; }
        [Display(Name = "Project Name")]
        public string project_Name { get; set; }
        [Display(Name = "Subject")]
        public string Meeting_Subject { get; set; }
        [Display(Name = "Objective")]
        public string Meeting_objective { get; set; }
        public string Agenda { get; set; }
        [Display(Name = "Agenda SubItem")]
        public string Agenda_SubItem { get; set; }
        [Display(Name = "Date")]
        public string MeetingDate { get; set; }
        [Display(Name = "Time")]
        public string MeetingTime { get; set; }
        [Display(Name = "Assigned To")]
        public string MeetingAssignedTo { get; set; }
        [Display(Name = "Reccurence")]
        public string reoccrence { get; set; }
        [Display(Name = "Location")]
        public string Meeting_Location { get; set; }
        public string Partipatents { get; set; }
        [Display(Name = "Link")]
        public string Share_Link { get; set; }
    }
}
