//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Meeting_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PollOption
    {
        public int PollOptionID { get; set; }
        public int PollID { get; set; }
        public string Answers { get; set; }
        public int Vote { get; set; }
    
        public virtual Poll Poll { get; set; }
    }
}
